#!/bin/bash

printenv

# tags from https://hub.docker.com/r/library/gcc/tags/
#GCC_TAG_VERSION_ARR=( 4.6 4.8 4.9 5.2 5.4 6.3 6.4 7.2 )
GCC_TAG_VERSION_ARR=( 4.6 4.8 )

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for GCC_TAG in "${GCC_TAG_VERSION_ARR[@]}"; do
	echo "Building docker image: $IMAGE_NAME-$GCC_TAG"
	
	export DOCKER_TAG=$GCC_TAG
	
	docker build \
	    --build-arg GCC_TAG=$GCC_TAG \
	    --tag $IMAGE_NAME .
	
#	docker build \
#	    --build-arg GCC_TAG=$GCC_TAG \
#	    --tag ${repoName}:$GCC_TAG .
done

#docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$SOURCE_COMMIT -t $IMAGE_NAME .

