#!/bin/bash

for GCC_TAG in "${GCC_TAG_VERSION_ARR[@]}"; do
	echo "Building docker image: $DOCKER_IMAGE_NAME:$GCC_TAG"
	docker build \
	    --build-arg GCC_TAG=$GCC_TAG \
	    --tag $IMAGE_NAME:$GCC_TAG .
done

#docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$SOURCE_COMMIT -t $IMAGE_NAME .


